/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdmin;

import UI.City.CityJPanel;
import model.Data;
import model.Person;

/**
 *
 * @author adityaraj
 */
public class SystemAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminJPanel
     */
    Person person;
    Data d;
    public SystemAdminJPanel(Data d,Person p) {
        initComponents();
        this.person = p;
        this.d = d;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPaneSystemAdmin = new javax.swing.JSplitPane();
        controlPanelSystemAdmin = new javax.swing.JPanel();
        btnManageCities = new javax.swing.JButton();
        btnManageEnterpriseAdmins = new javax.swing.JButton();
        btnManagePerson = new javax.swing.JButton();
        btnCharts = new javax.swing.JButton();
        workAreaSystemAdmin = new javax.swing.JPanel();

        jSplitPaneSystemAdmin.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        controlPanelSystemAdmin.setBackground(new java.awt.Color(204, 204, 255));

        btnManageCities.setBackground(new java.awt.Color(204, 255, 204));
        btnManageCities.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        btnManageCities.setForeground(new java.awt.Color(0, 0, 102));
        btnManageCities.setText("Manage Cities");
        btnManageCities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCitiesActionPerformed(evt);
            }
        });

        btnManageEnterpriseAdmins.setBackground(new java.awt.Color(204, 255, 204));
        btnManageEnterpriseAdmins.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        btnManageEnterpriseAdmins.setForeground(new java.awt.Color(0, 0, 102));
        btnManageEnterpriseAdmins.setText("Manage Enterprise Admins");
        btnManageEnterpriseAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterpriseAdminsActionPerformed(evt);
            }
        });

        btnManagePerson.setBackground(new java.awt.Color(204, 255, 204));
        btnManagePerson.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        btnManagePerson.setForeground(new java.awt.Color(0, 0, 102));
        btnManagePerson.setText("Manage Person");

        btnCharts.setBackground(new java.awt.Color(204, 255, 204));
        btnCharts.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        btnCharts.setForeground(new java.awt.Color(0, 0, 102));
        btnCharts.setText("Charts");

        javax.swing.GroupLayout controlPanelSystemAdminLayout = new javax.swing.GroupLayout(controlPanelSystemAdmin);
        controlPanelSystemAdmin.setLayout(controlPanelSystemAdminLayout);
        controlPanelSystemAdminLayout.setHorizontalGroup(
            controlPanelSystemAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelSystemAdminLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnManageCities)
                .addGap(18, 18, 18)
                .addComponent(btnManageEnterpriseAdmins)
                .addGap(18, 18, 18)
                .addComponent(btnManagePerson)
                .addGap(18, 18, 18)
                .addComponent(btnCharts)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        controlPanelSystemAdminLayout.setVerticalGroup(
            controlPanelSystemAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelSystemAdminLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(controlPanelSystemAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageCities)
                    .addComponent(btnManageEnterpriseAdmins)
                    .addComponent(btnManagePerson)
                    .addComponent(btnCharts))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jSplitPaneSystemAdmin.setTopComponent(controlPanelSystemAdmin);

        workAreaSystemAdmin.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout workAreaSystemAdminLayout = new javax.swing.GroupLayout(workAreaSystemAdmin);
        workAreaSystemAdmin.setLayout(workAreaSystemAdminLayout);
        workAreaSystemAdminLayout.setHorizontalGroup(
            workAreaSystemAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 773, Short.MAX_VALUE)
        );
        workAreaSystemAdminLayout.setVerticalGroup(
            workAreaSystemAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        jSplitPaneSystemAdmin.setRightComponent(workAreaSystemAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneSystemAdmin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneSystemAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCitiesActionPerformed
        // TODO add your handling code here:
        CityJPanel cityPanel = new CityJPanel(d);
        jSplitPaneSystemAdmin.setRightComponent(cityPanel);
    }//GEN-LAST:event_btnManageCitiesActionPerformed

    private void btnManageEnterpriseAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterpriseAdminsActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseAdmins manageEAdmins = new ManageEnterpriseAdmins(d);
        jSplitPaneSystemAdmin.setRightComponent(manageEAdmins);
    }//GEN-LAST:event_btnManageEnterpriseAdminsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCharts;
    private javax.swing.JButton btnManageCities;
    private javax.swing.JButton btnManageEnterpriseAdmins;
    private javax.swing.JButton btnManagePerson;
    private javax.swing.JPanel controlPanelSystemAdmin;
    private javax.swing.JSplitPane jSplitPaneSystemAdmin;
    private javax.swing.JPanel workAreaSystemAdmin;
    // End of variables declaration//GEN-END:variables

}
