/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.users;

import UI.FoodService.AddViewFood;
import model.Data;
import model.Person;

/**
 *
 * @author adityaraj
 */
public class UserPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserPanel
     */
    Data d;
    Person p;
    public UserPanel(Data d, Person p) {
        initComponents();
        this.d = d;
        this.p = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPaneUserPanel = new javax.swing.JSplitPane();
        controlPanelUser = new javax.swing.JPanel();
        btnFindFoods = new javax.swing.JButton();
        btnFindClothes = new javax.swing.JButton();
        btnFindVolunteers = new javax.swing.JButton();
        btnFindHousing = new javax.swing.JButton();
        workAreaUser = new javax.swing.JPanel();

        jSplitPaneUserPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        btnFindFoods.setText("Find Foods Near You!");
        btnFindFoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindFoodsActionPerformed(evt);
            }
        });

        btnFindClothes.setText("Find Clothes Near You!");
        btnFindClothes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindClothesActionPerformed(evt);
            }
        });

        btnFindVolunteers.setText("Find Volunteers");

        btnFindHousing.setText("Find Housing");

        javax.swing.GroupLayout controlPanelUserLayout = new javax.swing.GroupLayout(controlPanelUser);
        controlPanelUser.setLayout(controlPanelUserLayout);
        controlPanelUserLayout.setHorizontalGroup(
            controlPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelUserLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnFindFoods)
                .addGap(28, 28, 28)
                .addComponent(btnFindClothes)
                .addGap(18, 18, 18)
                .addComponent(btnFindVolunteers)
                .addGap(18, 18, 18)
                .addComponent(btnFindHousing)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        controlPanelUserLayout.setVerticalGroup(
            controlPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelUserLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(controlPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFindFoods)
                    .addComponent(btnFindClothes)
                    .addComponent(btnFindVolunteers)
                    .addComponent(btnFindHousing))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jSplitPaneUserPanel.setTopComponent(controlPanelUser);

        javax.swing.GroupLayout workAreaUserLayout = new javax.swing.GroupLayout(workAreaUser);
        workAreaUser.setLayout(workAreaUserLayout);
        workAreaUserLayout.setHorizontalGroup(
            workAreaUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        workAreaUserLayout.setVerticalGroup(
            workAreaUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        jSplitPaneUserPanel.setRightComponent(workAreaUser);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneUserPanel)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindFoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindFoodsActionPerformed
        // TODO add your handling code here:
        FindFoodsPanel findFood = new FindFoodsPanel(d, p);
        jSplitPaneUserPanel.setRightComponent(findFood);
    }//GEN-LAST:event_btnFindFoodsActionPerformed

    private void btnFindClothesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindClothesActionPerformed
        // TODO add your handling code here:
        FindHousingPanel findHousingPanel = new FindHousingPanel(d, p);
        jSplitPaneUserPanel.setRightComponent(findHousingPanel);
    }//GEN-LAST:event_btnFindClothesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFindClothes;
    private javax.swing.JButton btnFindFoods;
    private javax.swing.JButton btnFindHousing;
    private javax.swing.JButton btnFindVolunteers;
    private javax.swing.JPanel controlPanelUser;
    private javax.swing.JSplitPane jSplitPaneUserPanel;
    private javax.swing.JPanel workAreaUser;
    // End of variables declaration//GEN-END:variables
}
