/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Volunteer;

/**
 *
 * @author akshitabarot
 */
public class ViewVolunteerServiceSysAdmin extends javax.swing.JPanel {

    /**
     * Creates new form ViewVolunteerServiceSysAdmin
     */
    public ViewVolunteerServiceSysAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEncounters = new javax.swing.JTable();
        btnViewVolunteerService = new javax.swing.JButton();
        btnUpdateVolunteerService = new javax.swing.JButton();
        btnDeleteVolunteerService = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jComboBoxVolunteerServiceManager = new javax.swing.JComboBox<>();
        txtVolunteerServiceLocation = new javax.swing.JTextField();
        jComboBoxVolunteerOrg = new javax.swing.JComboBox<>();

        jLabel1.setText("View Volunteer Service");

        tblEncounters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Volunteer Organisation", "Location", "Volunteer Manager"
            }
        ));
        jScrollPane1.setViewportView(tblEncounters);

        btnViewVolunteerService.setText("View Volunteer Service");
        btnViewVolunteerService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewVolunteerServiceActionPerformed(evt);
            }
        });

        btnUpdateVolunteerService.setText("Update Volunteer Service");
        btnUpdateVolunteerService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateVolunteerServiceActionPerformed(evt);
            }
        });

        btnDeleteVolunteerService.setText("Delete Volunteer Service");
        btnDeleteVolunteerService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVolunteerServiceActionPerformed(evt);
            }
        });

        jLabel2.setText("Volunteer Organisation");

        jLabel42.setText("Location");

        jLabel43.setText("Volunteer Manager");

        jComboBoxVolunteerOrg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NGO", "College", "Self" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxVolunteerServiceManager, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxVolunteerOrg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtVolunteerServiceLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnViewVolunteerService)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateVolunteerService)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteVolunteerService)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewVolunteerService)
                    .addComponent(btnUpdateVolunteerService)
                    .addComponent(btnDeleteVolunteerService))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel42)
                        .addGap(18, 22, Short.MAX_VALUE)
                        .addComponent(jLabel43)
                        .addGap(99, 99, 99))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxVolunteerOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtVolunteerServiceLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxVolunteerServiceManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewVolunteerServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewVolunteerServiceActionPerformed
        // TODO add your handling code here:

       
    }//GEN-LAST:event_btnViewVolunteerServiceActionPerformed

    private void btnUpdateVolunteerServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateVolunteerServiceActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnUpdateVolunteerServiceActionPerformed

    private void btnDeleteVolunteerServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVolunteerServiceActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_btnDeleteVolunteerServiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteVolunteerService;
    private javax.swing.JButton btnUpdateVolunteerService;
    private javax.swing.JButton btnViewVolunteerService;
    private javax.swing.JComboBox<String> jComboBoxVolunteerOrg;
    private javax.swing.JComboBox<Object> jComboBoxVolunteerServiceManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEncounters;
    private javax.swing.JTextField txtVolunteerServiceLocation;
    // End of variables declaration//GEN-END:variables
}
