/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Volunteer;

/**
 *
 * @author akshitabarot
 */
public class VolunteerServiceAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerServiceAdminPanel
     */
    public VolunteerServiceAdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsplitPanelvolunteerServiceAdmin = new javax.swing.JSplitPane();
        controlPanelVolunteerServiceAdmin = new javax.swing.JPanel();
        btnManageVolunteerService = new javax.swing.JButton();
        workAreaVolunteerServiceAdmin = new javax.swing.JPanel();

        jsplitPanelvolunteerServiceAdmin.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        controlPanelVolunteerServiceAdmin.setBackground(new java.awt.Color(204, 204, 255));
        controlPanelVolunteerServiceAdmin.setPreferredSize(new java.awt.Dimension(824, 120));

        btnManageVolunteerService.setBackground(new java.awt.Color(204, 255, 204));
        btnManageVolunteerService.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        btnManageVolunteerService.setForeground(new java.awt.Color(0, 0, 102));
        btnManageVolunteerService.setText("Manage Volunteer Services");
        btnManageVolunteerService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVolunteerServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelVolunteerServiceAdminLayout = new javax.swing.GroupLayout(controlPanelVolunteerServiceAdmin);
        controlPanelVolunteerServiceAdmin.setLayout(controlPanelVolunteerServiceAdminLayout);
        controlPanelVolunteerServiceAdminLayout.setHorizontalGroup(
            controlPanelVolunteerServiceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelVolunteerServiceAdminLayout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(btnManageVolunteerService)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        controlPanelVolunteerServiceAdminLayout.setVerticalGroup(
            controlPanelVolunteerServiceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelVolunteerServiceAdminLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(btnManageVolunteerService)
                .addGap(19, 19, 19))
        );

        jsplitPanelvolunteerServiceAdmin.setTopComponent(controlPanelVolunteerServiceAdmin);

        workAreaVolunteerServiceAdmin.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout workAreaVolunteerServiceAdminLayout = new javax.swing.GroupLayout(workAreaVolunteerServiceAdmin);
        workAreaVolunteerServiceAdmin.setLayout(workAreaVolunteerServiceAdminLayout);
        workAreaVolunteerServiceAdminLayout.setHorizontalGroup(
            workAreaVolunteerServiceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
        );
        workAreaVolunteerServiceAdminLayout.setVerticalGroup(
            workAreaVolunteerServiceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        jsplitPanelvolunteerServiceAdmin.setRightComponent(workAreaVolunteerServiceAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsplitPanelvolunteerServiceAdmin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsplitPanelvolunteerServiceAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageVolunteerServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVolunteerServiceActionPerformed
        // TODO add your handling code here:
        AddVolunteerServicePanel addVolunteerService = new AddVolunteerServicePanel();
        jsplitPanelvolunteerServiceAdmin.setRightComponent(addVolunteerService);
        
    }//GEN-LAST:event_btnManageVolunteerServiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageVolunteerService;
    private javax.swing.JPanel controlPanelVolunteerServiceAdmin;
    private javax.swing.JSplitPane jsplitPanelvolunteerServiceAdmin;
    private javax.swing.JPanel workAreaVolunteerServiceAdmin;
    // End of variables declaration//GEN-END:variables
}
