/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.HousingService;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Data;
import model.Enterprise.Enterprise;
import model.Organisation.Organisation;
import model.Person;
import model.city.Address;
import model.city.City;
import model.city.Community;

/**
 *
 * @author anupamaditya
 */
public class HousingServiceAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form HousingServiceAdminPanel
     */
    
    Data d;
    Person p;
    public HousingServiceAdminPanel(Data d, Person p) {
        initComponents();
        this.d =d;
        this.p =p;
        populateAddressTable();
        populateHousingOrganisationTable();
        populateRestaurantManagers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHousingOrganisation = new javax.swing.JTable();
        BtnViewOrganisation = new javax.swing.JButton();
        BtnDeleteOrganisation = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtOrganisationId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxOrganisationType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtOrganisationName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxLocation = new javax.swing.JComboBox<>();
        jComboBoxHousingServiceManager = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPhoneNo = new javax.swing.JTextField();
        btnAddHousingService = new javax.swing.JButton();
        BtnUpdateHousingOrganisation = new javax.swing.JButton();

        tblHousingOrganisation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "OrganisationId", "Organisation Name", "Organisation Type", "Location", "Organisation Manager", "Phone Number"
            }
        ));
        jScrollPane1.setViewportView(tblHousingOrganisation);

        BtnViewOrganisation.setText("View Organisation");

        BtnDeleteOrganisation.setText("Delete Organisation");

        jLabel5.setText("Organisatin ID");

        jLabel1.setText("Organisation Type");

        jComboBoxOrganisationType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Residents", "College Dorms", "NGO" }));

        jLabel4.setText("Organisation Name");

        jLabel2.setText("Location");

        jLabel3.setText("Service Manager");

        jLabel6.setText("Phone No");

        btnAddHousingService.setText("Add Organisation");
        btnAddHousingService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHousingServiceActionPerformed(evt);
            }
        });

        BtnUpdateHousingOrganisation.setText("Update Organisation");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxHousingServiceManager, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxOrganisationType, 0, 150, Short.MAX_VALUE)
                    .addComponent(txtOrganisationName)
                    .addComponent(jComboBoxLocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtOrganisationId)
                    .addComponent(txtPhoneNo))
                .addGap(229, 229, 229))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnViewOrganisation)
                        .addGap(35, 35, 35)
                        .addComponent(BtnDeleteOrganisation))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddHousingService)
                        .addGap(18, 18, 18)
                        .addComponent(BtnUpdateHousingOrganisation)
                        .addGap(171, 171, 171)))
                .addContainerGap(74, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnViewOrganisation)
                    .addComponent(BtnDeleteOrganisation))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtOrganisationId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxOrganisationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrganisationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxHousingServiceManager, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddHousingService)
                    .addComponent(BtnUpdateHousingOrganisation))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddHousingServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHousingServiceActionPerformed
        // TODO add your handling code here:
        String organisationType = String.valueOf(jComboBoxOrganisationType.getSelectedItem());
        String organisationName = String.valueOf(txtOrganisationName.getText());
        Person p = (Person)jComboBoxHousingServiceManager.getSelectedItem();
        String phoneNo = txtPhoneNo.getText();
        Address location = (Address)jComboBoxLocation.getSelectedItem();
        /*
        if(jComboBoxCities.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this, "Select City");
            return;
        }
        City c = (City)jComboBoxCities.getSelectedItem();
        */
        if(jComboBoxOrganisationType.getSelectedItem()==null || organisationName.length()==0 || phoneNo.length()<10){
            JOptionPane.showMessageDialog(this, "Enter All fields correctly");
            return;
        }

        int v=0;
        try {
            Enterprise e = d.getEnterpriseDirectory().getEnterprise(Enterprise.EnterpriseType.HousingService);
            v = d.addOrganisation(organisationType,organisationName,location,p,phoneNo,"HousingService",e.getEnterpriseId());
        } catch (SQLException ex ) {
            Logger.getLogger(HousingServiceAdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(v==0){
            JOptionPane.showMessageDialog(this, "Error in creating Organisation");
            return;
        }
        txtOrganisationId.setText("");
        txtOrganisationName.setText("");
        txtPhoneNo.setText("");
        jComboBoxHousingServiceManager.setSelectedItem(null);
        jComboBoxLocation.setSelectedItem(null);
        jComboBoxOrganisationType.setSelectedItem(null);

        JOptionPane.showMessageDialog(this, "City Info Saved");
        populateHousingOrganisationTable();
    }//GEN-LAST:event_btnAddHousingServiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDeleteOrganisation;
    private javax.swing.JButton BtnUpdateHousingOrganisation;
    private javax.swing.JButton BtnViewOrganisation;
    private javax.swing.JButton btnAddHousingService;
    private javax.swing.JComboBox<Object> jComboBoxHousingServiceManager;
    private javax.swing.JComboBox<Object> jComboBoxLocation;
    private javax.swing.JComboBox<String> jComboBoxOrganisationType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHousingOrganisation;
    private javax.swing.JTextField txtOrganisationId;
    private javax.swing.JTextField txtOrganisationName;
    private javax.swing.JTextField txtPhoneNo;
    // End of variables declaration//GEN-END:variables

    private void populateHousingOrganisationTable() {
        DefaultTableModel model = (DefaultTableModel) tblHousingOrganisation.getModel();
               model.setRowCount(0);
               
               for(Organisation o: d.getEnterpriseDirectory().getEnterprise(Enterprise.EnterpriseType.HousingService).getOrganisationDirectory().getOrganisationList()){
                    Object[] row = new Object[6];
                     row[0] = o.getOrganisationId();
                     row[1] = o.getOrganisationName();
                     row[2] = o.getOrganisationType();
                     row[3] = o.getAddress().getStreetAddress();
                     row[4] = o.getPerson().getUserName();
                     row[5] = o.getPhoneNo();
                     model.addRow(row);
                     
        }
    }
    private void populateRestaurantManagers() {
        //left to implement
         List<Person> managers = d.getManagers();
        jComboBoxHousingServiceManager.removeAllItems();
        for(Person p : managers){
            jComboBoxHousingServiceManager.addItem(p);
            
            
            
        }
        
    }

    private void populateAddressTable() {
        List<City> cities = d.getCities();
        jComboBoxLocation.removeAllItems();
        for(City c : cities){
            for(Community comm : c.getCommunityList()){
                for(Address add : comm.getHouseList()){
                    jComboBoxLocation.addItem(add);
                }
                
            }
        
        }
    }
 }

