/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.ClothesService;

/**
 *
 * @author adityaraj
 */
public class ClothesServiceAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClothesServiceAdminPanel
     */
    public ClothesServiceAdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsplitPanelclothesServiceAdmin = new javax.swing.JSplitPane();
        controlPanelClothesServiceAdmin = new javax.swing.JPanel();
        btnAddClothesService = new javax.swing.JButton();
        btnAddRemoveClothesService = new javax.swing.JButton();
        workAreaClothesServiceAdmin = new javax.swing.JPanel();

        jsplitPanelclothesServiceAdmin.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        btnAddClothesService.setText("Add Service");
        btnAddClothesService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClothesServiceActionPerformed(evt);
            }
        });

        btnAddRemoveClothesService.setText("Approve/Reject Clothes Service");
        btnAddRemoveClothesService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRemoveClothesServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelClothesServiceAdminLayout = new javax.swing.GroupLayout(controlPanelClothesServiceAdmin);
        controlPanelClothesServiceAdmin.setLayout(controlPanelClothesServiceAdminLayout);
        controlPanelClothesServiceAdminLayout.setHorizontalGroup(
            controlPanelClothesServiceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelClothesServiceAdminLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btnAddClothesService)
                .addGap(59, 59, 59)
                .addComponent(btnAddRemoveClothesService)
                .addContainerGap(293, Short.MAX_VALUE))
        );
        controlPanelClothesServiceAdminLayout.setVerticalGroup(
            controlPanelClothesServiceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelClothesServiceAdminLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(controlPanelClothesServiceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddClothesService)
                    .addComponent(btnAddRemoveClothesService))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jsplitPanelclothesServiceAdmin.setTopComponent(controlPanelClothesServiceAdmin);

        javax.swing.GroupLayout workAreaClothesServiceAdminLayout = new javax.swing.GroupLayout(workAreaClothesServiceAdmin);
        workAreaClothesServiceAdmin.setLayout(workAreaClothesServiceAdminLayout);
        workAreaClothesServiceAdminLayout.setHorizontalGroup(
            workAreaClothesServiceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );
        workAreaClothesServiceAdminLayout.setVerticalGroup(
            workAreaClothesServiceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        jsplitPanelclothesServiceAdmin.setRightComponent(workAreaClothesServiceAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsplitPanelclothesServiceAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsplitPanelclothesServiceAdmin)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddClothesServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClothesServiceActionPerformed
        // TODO add your handling code here:
        AddClothesServicePanel addClothesService = new AddClothesServicePanel();
        jsplitPanelclothesServiceAdmin.setRightComponent(addClothesService);
    }//GEN-LAST:event_btnAddClothesServiceActionPerformed

    private void btnAddRemoveClothesServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRemoveClothesServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddRemoveClothesServiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddClothesService;
    private javax.swing.JButton btnAddRemoveClothesService;
    private javax.swing.JPanel controlPanelClothesServiceAdmin;
    private javax.swing.JSplitPane jsplitPanelclothesServiceAdmin;
    private javax.swing.JPanel workAreaClothesServiceAdmin;
    // End of variables declaration//GEN-END:variables
}
