/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.VolunteerService;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Data;
import model.Enterprise.Enterprise;
import model.Organisation.Organisation;
import model.Person;
import model.city.Address;
import model.city.City;
import model.city.Community;

/**
 *
 * @author anupamaditya
 */
public class VolunteerServiceAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerServiceAdminPanel
     */
    
    Data d;
    Person p;
    public VolunteerServiceAdminPanel(Data d, Person p) {
        initComponents();
        this.d = d;
        this.p=p;
        populateVolunteerOrganisationTable();
        populateRestaurantManagers();
        populateAddressTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVolunteerOrganisation = new javax.swing.JTable();
        BtnViewOrganisation = new javax.swing.JButton();
        BtnDeleteOrganisation = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtOrganisationId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxOrganisationType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtOrganisationName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxLocation = new javax.swing.JComboBox<>();
        jComboBoxVolunteerServiceManager = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPhoneNo = new javax.swing.JTextField();
        btnAddVolunteerService = new javax.swing.JButton();
        BtnUpdateVolunteerOrganisation = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        tblVolunteerOrganisation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "OrganisationId", "Organisation Name", "Organisation Type", "Location", "Organisation Manager", "Phone Number"
            }
        ));
        jScrollPane1.setViewportView(tblVolunteerOrganisation);

        BtnViewOrganisation.setBackground(new java.awt.Color(204, 255, 204));
        BtnViewOrganisation.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        BtnViewOrganisation.setForeground(new java.awt.Color(0, 0, 102));
        BtnViewOrganisation.setText("View Organisation");

        BtnDeleteOrganisation.setBackground(new java.awt.Color(204, 255, 204));
        BtnDeleteOrganisation.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        BtnDeleteOrganisation.setForeground(new java.awt.Color(0, 0, 102));
        BtnDeleteOrganisation.setText("Delete Organisation");

        jLabel5.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Organisatin ID");

        jLabel1.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Organisation Type");

        jComboBoxOrganisationType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Residents", "College", "NGO" }));

        jLabel4.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Organisation Name");

        jLabel2.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Location");

        jLabel3.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Service Manager");

        jLabel6.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Phone No");

        btnAddVolunteerService.setBackground(new java.awt.Color(204, 255, 204));
        btnAddVolunteerService.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        btnAddVolunteerService.setForeground(new java.awt.Color(0, 0, 102));
        btnAddVolunteerService.setText("Add Organisation");
        btnAddVolunteerService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVolunteerServiceActionPerformed(evt);
            }
        });

        BtnUpdateVolunteerOrganisation.setBackground(new java.awt.Color(204, 255, 204));
        BtnUpdateVolunteerOrganisation.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        BtnUpdateVolunteerOrganisation.setForeground(new java.awt.Color(0, 0, 102));
        BtnUpdateVolunteerOrganisation.setText("Update Organisation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(BtnViewOrganisation)
                .addGap(19, 19, 19)
                .addComponent(BtnDeleteOrganisation))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel5)
                .addGap(111, 111, 111)
                .addComponent(txtOrganisationId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jComboBoxOrganisationType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel4)
                .addGap(81, 81, 81)
                .addComponent(txtOrganisationName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jComboBoxLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jComboBoxVolunteerServiceManager, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(btnAddVolunteerService)
                .addGap(17, 17, 17)
                .addComponent(BtnUpdateVolunteerOrganisation))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnViewOrganisation)
                    .addComponent(BtnDeleteOrganisation))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5))
                    .addComponent(txtOrganisationId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1))
                    .addComponent(jComboBoxOrganisationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4))
                    .addComponent(txtOrganisationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2))
                    .addComponent(jComboBoxLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(jComboBoxVolunteerServiceManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddVolunteerService)
                    .addComponent(BtnUpdateVolunteerOrganisation)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddVolunteerServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVolunteerServiceActionPerformed
        // TODO add your handling code here:
        String organisationType = String.valueOf(jComboBoxOrganisationType.getSelectedItem());
        String organisationName = String.valueOf(txtOrganisationName.getText());
        Person p = (Person)jComboBoxVolunteerServiceManager.getSelectedItem();
        String phoneNo = txtPhoneNo.getText();
        Address location = (Address)jComboBoxLocation.getSelectedItem();
        /*
        if(jComboBoxCities.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this, "Select City");
            return;
        }
        City c = (City)jComboBoxCities.getSelectedItem();
        */
        if(jComboBoxOrganisationType.getSelectedItem()==null || organisationName.length()==0 || phoneNo.length()<10){
            JOptionPane.showMessageDialog(this, "Enter All fields correctly");
            return;
        }

        int v=0;
        try {
            Enterprise e = d.getEnterpriseDirectory().getEnterprise(Enterprise.EnterpriseType.FoodService);
            v = d.addOrganisation(organisationType,organisationName,location,p,phoneNo,organisationType,e.getEnterpriseId());
        } catch (SQLException ex ) {
            Logger.getLogger(VolunteerServiceAdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(v==0){
            JOptionPane.showMessageDialog(this, "Error in creating Organisation");
            return;
        }
        txtOrganisationId.setText("");
        txtOrganisationName.setText("");
        txtPhoneNo.setText("");
        jComboBoxVolunteerServiceManager.setSelectedItem(null);
        jComboBoxLocation.setSelectedItem(null);
        jComboBoxOrganisationType.setSelectedItem(null);

        JOptionPane.showMessageDialog(this, "City Info Saved");
        populateVolunteerOrganisationTable();
    }//GEN-LAST:event_btnAddVolunteerServiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDeleteOrganisation;
    private javax.swing.JButton BtnUpdateVolunteerOrganisation;
    private javax.swing.JButton BtnViewOrganisation;
    private javax.swing.JButton btnAddVolunteerService;
    private javax.swing.JComboBox<Object> jComboBoxLocation;
    private javax.swing.JComboBox<String> jComboBoxOrganisationType;
    private javax.swing.JComboBox<Object> jComboBoxVolunteerServiceManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVolunteerOrganisation;
    private javax.swing.JTextField txtOrganisationId;
    private javax.swing.JTextField txtOrganisationName;
    private javax.swing.JTextField txtPhoneNo;
    // End of variables declaration//GEN-END:variables

    private void populateVolunteerOrganisationTable() {
        DefaultTableModel model = (DefaultTableModel) tblVolunteerOrganisation.getModel();
               model.setRowCount(0);
               
               for(Organisation o: d.getEnterpriseDirectory().getEnterprise(Enterprise.EnterpriseType.VolunteerService).getOrganisationDirectory().getOrganisationList()){
                    Object[] row = new Object[6];
                     row[0] = o.getOrganisationId();
                     row[1] = o.getOrganisationName();
                     row[2] = o.getOrganisationType();
                     row[3] = o.getAddress().getStreetAddress();
                     row[4] = o.getPerson().getUserName();
                     row[5] = o.getPhoneNo();
                     model.addRow(row);
                     
        }
    }
     private void populateRestaurantManagers() {
         //left to implement
//         List<Person> managers = d.getManagers();
//        jComboBoxVolunteerServiceManager.removeAllItems();
//        for(Person p : managers){
//            jComboBoxVolunteerServiceManager.addItem(p);
//            
//            
//            
//        }
        
    }

    private void populateAddressTable() {
        List<City> cities = d.getCities();
        jComboBoxLocation.removeAllItems();
        for(City c : cities){
            for(Community comm : c.getCommunityList()){
                for(Address add : comm.getHouseList()){
                    jComboBoxLocation.addItem(add);
                }
                
            }
        
        }
    }   
}

