/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.FoodService;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Data;
import model.Enterprise.Enterprise;
import model.Organisation.Organisation;
import model.Organisation.OrganisationDirectory;
import model.Person;
import model.city.Address;
import model.city.City;
import model.city.Community;

/**
 *
 * @author anupamaditya
 */
public class FoodServiceAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form FoodServiceAdminPanel
     */
    
    Data d;
    Person p;

    public FoodServiceAdminPanel(Data d, Person p) {
        initComponents();
        this.d =d;
        this.p =p;
        txtOrganisationId.setEditable(false);
        populateFoodOrganisationTable();
        populateRestaurantManagers();       
        populateAddressTable();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxOrganisationType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtOrganisationName = new javax.swing.JTextField();
        btnAddFoodService = new javax.swing.JButton();
        jComboBoxFoodServiceManager = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFoodOrganisation = new javax.swing.JTable();
        jComboBoxLocation = new javax.swing.JComboBox<>();
        BtnViewOrganisation = new javax.swing.JButton();
        BtnUpdateOrganisation = new javax.swing.JButton();
        BtnDeleteOrganisation = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtOrganisationId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPhoneNo = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Organisation Type");

        jLabel3.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Service Manager");

        jComboBoxOrganisationType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Restaurant", "Residents", "College", "NGO" }));

        jLabel4.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Organisation Name");

        btnAddFoodService.setBackground(new java.awt.Color(204, 255, 204));
        btnAddFoodService.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        btnAddFoodService.setForeground(new java.awt.Color(0, 0, 102));
        btnAddFoodService.setText("Add Organisation");
        btnAddFoodService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFoodServiceActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Location");

        tblFoodOrganisation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "OrganisationId", "Organisation Name", "Organisation Type", "Location", "Organisation Manager", "Phone Number"
            }
        ));
        jScrollPane1.setViewportView(tblFoodOrganisation);

        BtnViewOrganisation.setBackground(new java.awt.Color(204, 255, 204));
        BtnViewOrganisation.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        BtnViewOrganisation.setForeground(new java.awt.Color(0, 0, 102));
        BtnViewOrganisation.setText("View Organisation");
        BtnViewOrganisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewOrganisationActionPerformed(evt);
            }
        });

        BtnUpdateOrganisation.setBackground(new java.awt.Color(204, 255, 204));
        BtnUpdateOrganisation.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        BtnUpdateOrganisation.setForeground(new java.awt.Color(0, 0, 102));
        BtnUpdateOrganisation.setText("Update Organisation");
        BtnUpdateOrganisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateOrganisationActionPerformed(evt);
            }
        });

        BtnDeleteOrganisation.setBackground(new java.awt.Color(204, 255, 204));
        BtnDeleteOrganisation.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        BtnDeleteOrganisation.setForeground(new java.awt.Color(0, 0, 102));
        BtnDeleteOrganisation.setText("Delete Organisation");

        jLabel5.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Organisatin ID");

        jLabel6.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Phone No");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(392, 392, 392)
                .addComponent(BtnViewOrganisation)
                .addGap(29, 29, 29)
                .addComponent(BtnDeleteOrganisation))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel5)
                .addGap(93, 93, 93)
                .addComponent(txtOrganisationId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jComboBoxOrganisationType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel4)
                .addGap(63, 63, 63)
                .addComponent(txtOrganisationName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jComboBoxLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jComboBoxFoodServiceManager, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(btnAddFoodService)
                .addGap(18, 18, 18)
                .addComponent(BtnUpdateOrganisation))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnViewOrganisation)
                    .addComponent(BtnDeleteOrganisation))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(txtOrganisationId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(jComboBoxOrganisationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(txtOrganisationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3))
                    .addComponent(jComboBoxLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxFoodServiceManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddFoodService)
                    .addComponent(BtnUpdateOrganisation)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFoodServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFoodServiceActionPerformed
        // TODO add your handling code here:
        String organisationType = String.valueOf(jComboBoxOrganisationType.getSelectedItem());
        String organisationName = String.valueOf(txtOrganisationName.getText());
        Person pS = (Person)jComboBoxFoodServiceManager.getSelectedItem();
        String phoneNo = txtPhoneNo.getText();
        Address location = (Address)jComboBoxLocation.getSelectedItem();
        /*
        if(jComboBoxCities.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this, "Select City");
            return;
        }
        City c = (City)jComboBoxCities.getSelectedItem();
        */
        if(jComboBoxOrganisationType.getSelectedItem()==null || organisationName.length()==0 || phoneNo.length()<10){
            JOptionPane.showMessageDialog(this, "Enter All fields correctly");
            return;
        }

        int v=0;
        try {
            Enterprise e = d.getEnterpriseDirectory().getEnterprise(Enterprise.EnterpriseType.FoodService);
            v = d.addOrganisation(organisationType, organisationName, location, pS, phoneNo, organisationType,e.getEnterpriseId());
        } catch (SQLException ex ) {
            Logger.getLogger(FoodServiceAdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(v==0){
            JOptionPane.showMessageDialog(this, "Error in creating Organisation");
            return;
        }
        txtOrganisationId.setText("");
        txtOrganisationName.setText("");
        txtPhoneNo.setText("");
        jComboBoxFoodServiceManager.setSelectedItem(null);
        jComboBoxLocation.setSelectedItem(null);
        jComboBoxOrganisationType.setSelectedItem(null);

        JOptionPane.showMessageDialog(this, "City Info Saved");
        populateFoodOrganisationTable();
    }//GEN-LAST:event_btnAddFoodServiceActionPerformed

    private void BtnViewOrganisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewOrganisationActionPerformed
        // TODO add your handling code here:
        
         int selectedRowIndex = tblFoodOrganisation.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select row to view the details");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblFoodOrganisation.getModel();
        Organisation o = (Organisation) model.getValueAt(selectedRowIndex, 0);
        txtOrganisationId.setText(String.valueOf(o.getOrganisationId()));
        txtOrganisationId.setEditable(false);
        txtOrganisationName.setText(String.valueOf(o.getOrganisationName()));
        txtOrganisationName.setEditable(true);
        txtPhoneNo.setText(String.valueOf(o.getPhoneNo()));
        txtPhoneNo.setEditable(true);
        jComboBoxFoodServiceManager.setSelectedItem(String.valueOf(o.getPerson()));
        jComboBoxFoodServiceManager.setEditable(true);
        jComboBoxLocation.setSelectedItem(String.valueOf(o.getAddress()));
        jComboBoxLocation.setEditable(true);
        jComboBoxOrganisationType.setSelectedItem(String.valueOf(o.getOrganisationType()));
        jComboBoxOrganisationType.setEditable(true);
        
    }//GEN-LAST:event_BtnViewOrganisationActionPerformed

    private void BtnUpdateOrganisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateOrganisationActionPerformed
        // TODO add your handling code here:
        
        try{
            
            if(txtOrganisationId.getText().length() == 0 || txtOrganisationName.getText().length()==0 || txtPhoneNo.getText().length()==0){
                JOptionPane.showMessageDialog(this, "Enter All fields");
                return;
            }
            
           Enterprise e = d.getEnterpriseDirectory().getEnterprise(Enterprise.EnterpriseType.FoodService);
            int v =d.updateOrganisation(txtOrganisationId.getText(), String.valueOf(jComboBoxOrganisationType.getSelectedItem()), txtOrganisationName.getText(), (Address)jComboBoxLocation.getSelectedItem(),(Person)jComboBoxFoodServiceManager.getSelectedItem(),txtPhoneNo.getText(),"FoodService",e.getEnterpriseId());
            //int v = data.updateOrganisation(String.valueOf(txtCityId.getText()),String.valueOf(txtCityName.getText()),txtCityState.getText());
            if(v==0){
                JOptionPane.showMessageDialog(this, "Error in Updating City Data");
                return;
            }
            JOptionPane.showMessageDialog(this, "City Info Updated");
            txtOrganisationId.setText("");
            txtOrganisationName.setText("");
            txtPhoneNo.setText("");
            jComboBoxFoodServiceManager.setSelectedItem(null);
            jComboBoxLocation.setSelectedItem(null);
            jComboBoxOrganisationType.setSelectedItem(null);
            populateFoodOrganisationTable();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Enter All fields");
            return;
        }
        populateFoodOrganisationTable();
    }//GEN-LAST:event_BtnUpdateOrganisationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDeleteOrganisation;
    private javax.swing.JButton BtnUpdateOrganisation;
    private javax.swing.JButton BtnViewOrganisation;
    private javax.swing.JButton btnAddFoodService;
    private javax.swing.JComboBox<Object> jComboBoxFoodServiceManager;
    private javax.swing.JComboBox<Object> jComboBoxLocation;
    private javax.swing.JComboBox<String> jComboBoxOrganisationType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFoodOrganisation;
    private javax.swing.JTextField txtOrganisationId;
    private javax.swing.JTextField txtOrganisationName;
    private javax.swing.JTextField txtPhoneNo;
    // End of variables declaration//GEN-END:variables

    private void populateFoodOrganisationTable() {
               DefaultTableModel model = (DefaultTableModel) tblFoodOrganisation.getModel();
               model.setRowCount(0);
               
               for(Organisation o: d.getEnterpriseDirectory().getEnterprise(Enterprise.EnterpriseType.FoodService).getOrganisationDirectory().getOrganisationList()){
                    Object[] row = new Object[6];
                     row[0] = o;
                     row[1] = o.getOrganisationName();
                     row[2] = o.getOrganisationType();
                     row[3] = o.getAddress().getStreetAddress();
                     row[4] = o.getPerson().getUserName();
                     row[5] = o.getPhoneNo();
                     model.addRow(row);
        }
      }

    private void populateRestaurantManagers() {
        //left to implement
         //List<Person> managers = d.getManagers();
        jComboBoxFoodServiceManager.removeAllItems();
//        for(Person p : managers){
//            jComboBoxFoodServiceManager.addItem(p);
//            
//            
//            
//        }
        
    }

    private void populateAddressTable() {
        List<City> cities = d.getCities();
        jComboBoxLocation.removeAllItems();
        for(City c : cities){
            for(Community comm : c.getCommunityList()){
                for(Address add : comm.getHouseList()){
                    jComboBoxLocation.addItem(add);
                }
                
            }
        
        }
    }
}

