/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Distribution;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Data;
import model.FoodDetails;
import model.HousingDetails;
import model.Person;

/**
 *
 * @author adityaraj
 */
public class DistributionHousingPanel extends javax.swing.JPanel {

    /**
     * Creates new form DistributionHousingPanel
     */
    Data d;
    Person p;
    public DistributionHousingPanel(Data d,Person p) {
        initComponents();
        this.d = d;
        this.p = p;
        populateHousing();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHousing = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        tblHousing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "HousingID", "Address", "Booking Date", "Available Beds", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblHousing);

        jButton1.setText("Approve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(0, 290, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblHousing.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select row to approve the request");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblHousing.getModel();
        HousingDetails h = (HousingDetails) model.getValueAt(selectedRowIndex, 0);
        int v = d.approveHousing(h);
        if(v==0){
            JOptionPane.showMessageDialog(this, "Error in Approving Foods");
            return;
        }
        populateHousing();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHousing;
    // End of variables declaration//GEN-END:variables

    private void populateHousing() {
        DefaultTableModel model = (DefaultTableModel) tblHousing.getModel();
        model.setRowCount(0);
        
        d.getHousingDetails();
        
        for(HousingDetails f : d.getHousingDirectory().getHousingDirectory()){
            Object[] row = new Object[5];
            row[0] = f;
            row[1] = f.getHousingAddress();
            row[2] = f.getBookingDate();
            row[3] = f.getAvailableBeds();
            row[4] = f.getStatus();
            
            model.addRow(row);
        }
    }
}
