/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Distribution;

import UI.FoodService.AddViewFood;
import model.Data;
import model.Person;

/**
 *
 * @author adityaraj
 */
public class DistributionManagePanel extends javax.swing.JPanel {

    /**
     * Creates new form DistributionManagePanel
     */
    Data d;
    Person p;
    public DistributionManagePanel(Data d, Person p) {
        initComponents();
        this.d = d;
        this.p = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPaneDistribution = new javax.swing.JSplitPane();
        controlPanelDistribution = new javax.swing.JPanel();
        btnDistributeFood = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        viewPanelDistribution = new javax.swing.JPanel();

        splitPaneDistribution.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        btnDistributeFood.setText("Distribute Food");
        btnDistributeFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDistributeFoodActionPerformed(evt);
            }
        });

        jButton2.setText("Distribute Clothes");

        jButton3.setText("Assign Volunteer");

        jButton4.setText("Lend Place");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelDistributionLayout = new javax.swing.GroupLayout(controlPanelDistribution);
        controlPanelDistribution.setLayout(controlPanelDistributionLayout);
        controlPanelDistributionLayout.setHorizontalGroup(
            controlPanelDistributionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelDistributionLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(btnDistributeFood)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        controlPanelDistributionLayout.setVerticalGroup(
            controlPanelDistributionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelDistributionLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(controlPanelDistributionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDistributeFood)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        splitPaneDistribution.setTopComponent(controlPanelDistribution);

        javax.swing.GroupLayout viewPanelDistributionLayout = new javax.swing.GroupLayout(viewPanelDistribution);
        viewPanelDistribution.setLayout(viewPanelDistributionLayout);
        viewPanelDistributionLayout.setHorizontalGroup(
            viewPanelDistributionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 774, Short.MAX_VALUE)
        );
        viewPanelDistributionLayout.setVerticalGroup(
            viewPanelDistributionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );

        splitPaneDistribution.setRightComponent(viewPanelDistribution);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPaneDistribution, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPaneDistribution)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDistributeFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDistributeFoodActionPerformed
        // TODO add your handling code here:
        DistributeFoodPanel distributeFood = new DistributeFoodPanel(d,p);
        splitPaneDistribution.setRightComponent(distributeFood);
    }//GEN-LAST:event_btnDistributeFoodActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DistributionHousingPanel distributehouse = new DistributionHousingPanel(d,p);
        splitPaneDistribution.setRightComponent(distributehouse);
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDistributeFood;
    private javax.swing.JPanel controlPanelDistribution;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JSplitPane splitPaneDistribution;
    private javax.swing.JPanel viewPanelDistribution;
    // End of variables declaration//GEN-END:variables
}
