/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Distribution;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ClothesDetails;
import model.Data;
import model.FoodDetails;
import model.Person;

/**
 *
 * @author anupamaditya
 */
public class DistributeClothesPanel extends javax.swing.JPanel {

    /**
     * Creates new form DistributeClothesPanel
     */
    Data d;
    Person p;
    public DistributeClothesPanel(Data d, Person p) {
        initComponents();
        this.d = d;
        this.p =p;
      populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClothes = new javax.swing.JTable();
        btnApprove = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        tblClothes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ClothesID", "Clothes category", "Clothes Quantity", "Clothes Name", "Organisation", "Clothes Status"
            }
        ));
        jScrollPane1.setViewportView(tblClothes);

        btnApprove.setBackground(new java.awt.Color(204, 255, 204));
        btnApprove.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        btnApprove.setForeground(new java.awt.Color(0, 0, 102));
        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnApprove)
                        .addGap(44, 44, 44)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnApprove)
                .addContainerGap(328, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        /*try{

            if(txtOrganisationId.getText().length() == 0 || txtOrganisationName.getText().length()==0 || txtPhoneNo.getText().length()==0){
                JOptionPane.showMessageDialog(this, "Enter All fields");
                return;
            }

            Enterprise e = d.getEnterpriseDirectory().getEnterprise(Enterprise.EnterpriseType.ClothesService);
            int v =d.updateOrganisation(txtOrganisationId.getText(), String.valueOf(jComboBoxOrganisationType.getSelectedItem()), txtOrganisationName.getText(), (Address)jComboBoxLocation.getSelectedItem(),(Person)jComboBoxClothesServiceManager.getSelectedItem(),txtPhoneNo.getText(),"ClothesService",e.getEnterpriseId());
            //int v = data.updateOrganisation(String.valueOf(txtCityId.getText()),String.valueOf(txtCityName.getText()),txtCityState.getText());
            if(v==0){
                JOptionPane.showMessageDialog(this, "Error in Updating Organisation Data");
                return;
            }
            JOptionPane.showMessageDialog(this, "Organisation Info Updated");
            txtOrganisationId.setText("");
            txtOrganisationName.setText("");
            txtPhoneNo.setText("");
            jComboBoxClothesServiceManager.setSelectedItem(null);
            jComboBoxLocation.setSelectedItem(null);
            jComboBoxOrganisationType.setSelectedItem(null);
            populateClothesOrganisationTable();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Enter All fields");
            return;
        }
        populateClothesOrganisationTable();*/
        int selectedRowIndex = tblClothes.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select row to approve the request");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblClothes.getModel();
        ClothesDetails c = (ClothesDetails) model.getValueAt(selectedRowIndex, 3);
        int v = d.approveClothes(c);
        if(v==0){
            JOptionPane.showMessageDialog(this, "Error in Approving Foods");
            return;
        }
        populateTable();

    }//GEN-LAST:event_btnApproveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClothes;
    // End of variables declaration//GEN-END:variables

 private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblClothes.getModel();
        model.setRowCount(0);
        
        d.getClothesDetails();
        
        for(ClothesDetails c : d.getClothesDirectory().getClothesDirectory()){
            Object[] row = new Object[6];
            row[0] = c.getClothesID();
            row[1] = c.getClothesCategory();
            row[2] = c.getClothesQuantity();
            row[4] = c.getOrg();
            row[5] = c.getClothesStatus();
            row[3] = c;
            model.addRow(row);
        }
    }
}
